baseURL = 'http://localhost:1313/activitylog'
defaultContentLanguage = 'de'
title = 'Trekko'
paginate = 9
mainSections = "activities"


[outputs]
  home = ["HTML", "humanstxt"]
  
  [outputFormats.humanstxt]
      baseName = "humans"
      isPlainText = true
      mediaType = "text/plain"

[languages]
  [languages.de]
      languageName = "Deutsch"

enableEmoji = true
enableRobotsTXT = true
canonifyURLs = true

[module]
  [module.hugoVersion]
    extended = true
    min = "0.87.0"
    
[params]
  ga_id=""
  mainSections = ["post"]
  disqus = "xxxxxxx"
  defaultImage = "https://michimauch.github.io/activitylog/headerimage.webp"
  matomoSiteID = "7"

  [params.meta_tags]
    meta_description = "Trekko - Unser Outdoor Journal."
    meta_og_title = "Trekko"
    meta_og_sitename = "Trekko"
    meta_og_type = "website"
    meta_og_url = "https://michimauch.github.io/activitylog/"
    meta_og_image = "https://michimauch.github.io/activitylog/headerimage.webp"
    meta_og_description = "Trekko - Unser Outdoor Journal."
    meta_twitter_card = "summary"
    meta_twitter_site = "@michimauch"
    meta_twitter_creator = "@michimauch"
    
 [params.humans_txt]
    dev_team = ""
    dev_github = ""
    thanks = ""
    standards = ""
    software = ""
    other_notes = ""
    
[markup]
    [markup.highlight]
        codeFences = true
        guessSyntax = true
        lineNos = false
        tabWidth = 4
        noClasses = false
        pygmentsUseClasses = true
        pygmentsCodefences = true

    [markup.goldmark]
        [markup.goldmark.renderer]
            unsafe= true   

    [markup.blackFriday]
        angledQuotes = true

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Alle Aktivitäten"
    url = "/activities/"
    weight = 2

[[menu.main]]
    name = "ViaGottardo"
    url = "/viagottardo/"
    weight = 3    

[[menu.main]]
    name = "Über Trekko"
    url = "/about/"
    weight = 4

[permalinks]
  posts = "/:year/:month/:day/:slug/"
  pages = "/:filename/"
  activities = "/activities/:slug"
